---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: tss-injector
  labels:
    app: tss
webhooks:
  - name: tss.thycotic.com
    clientConfig:
      service:
        name: tss-injector
        namespace: default
        path: "/inject"
        port: 8543
      caBundle: ""
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["secrets"]
