---
apiVersion: v1
kind: Secret
metadata:
  name: user-domain-pass
  annotations:
    tss.secretsvaultcloud.com/set-secret: "1"
type: Opaque
data:
  username: dW5tb2RpZmllZC11c2VybmFtZQ==
  domain: bXlkb21haW4K
  private-key: b21pdHRlZAo=
