---
apiVersion: v1
kind: Secret
metadata:
  name: pass-domain
  annotations:
    tss.secretsvaultcloud.com/update-secret: "1"
type: Opaque
data:
  password: dW5tb2RpZmllZC1wYXNzd29yZA==
  private-key: b21pdHRlZAo=
