apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tss.name" . }}-tls
data:
  cert: {{ .Files.Get (printf "%s.pem" (include "tss.name" .)) | b64enc }}
  key: {{ .Files.Get (printf "%s.key" (include "tss.name" .)) | b64enc }}
type: Opaque
