---
{{- $cert := genSelfSignedCert (include "tss.dnsname" .) nil (list (include "tss.dnsname" .) (include "tss.name" .)) (default 365 .Values.webhookCertExpireDays | int) -}}
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" -}}
apiVersion: admissionregistration.k8s.io/v1
{{- else }}
apiVersion: admissionregistration.k8s.io/v1beta1
{{- end }}
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "tss.name" . }}
  labels:
    {{- include "tss.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "tss.dnsname" . }}
    failurePolicy: Fail
    rules:
      - apiGroups: [""]
        apiVersions: ["v1", "v1beta1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["secrets"]
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
        scope: {{ default "*" .Values.webhookScope }}
{{- end }}
    clientConfig:
      caBundle: {{ $cert.Cert | b64enc }}
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "tss.name" . }}
        path: {{ .Values.webhookUri }}
{{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }}
        port: {{ .Values.webhookPort }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: {{ default "None" .Values.sideEffects }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tss.name" . }}-tls
data:
  cert: {{ $cert.Cert | b64enc }}
  key: {{ $cert.Key | b64enc }}
type: Opaque
